anime/anime/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('animeapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

anime/animeapp/urls.py
from . import views
from django.urls import path
app_name='animeapp'

urlpatterns = [
    path('', views.index, name='home'),
    path('anime/<int:anime_id>/',views.detail,name='detail'),
    path('add/',views.add_anime,name='add_anime'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

    ]

anime/animeapp/models.py
from django.db import models

# Create your models here.
class Anime(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    seasons=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

anime/animeapp/forms.py
from django import forms
from . models import Anime

class AnimeForm(forms.ModelForm):
    class Meta:
        model = Anime
        fields = ['name', 'desc', 'seasons', 'img']

anime/animeapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect

from . import forms
from . forms import AnimeForm
from .models import Anime


# Create your views here.
def index(request):
    anime=Anime.objects.all()
    context={
        'anime_list':anime
    }
    return render(request,'index.html',context)

def detail(request,anime_id):
    anime=Anime.objects.get(id=anime_id)
    return render(request,'detail.html',{'anime':anime})

def add_anime(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        seasons = request.POST.get('seasons')
        img = request.FILES['img']
        anime=Anime(name=name,desc=desc,seasons=seasons,img=img)
        anime.save()
    return render(request,'add.html')

def update(request,id):
    anime=Anime.objects.get(id=id)
    form=AnimeForm(request.POST or None, request.FILES, instance=anime)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'anime':anime})
def delete(request,id):
    if request.method=='POST':
        anime=Anime.objects.get(id=id)
        anime.delete()
        return redirect('/')
    return render(request,'delete.html')

anime/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="add_fun"></div>
    <form method="post" enctype="multipart/form-data" style="position:absolute;top:10%;left:45%;">
        {% csrf_token %}
        <p style="font-weight:bold;">Enter the anime name:</p>
        <input type="text" name="name" placeholder="Enter the Anime Name"><br>
        <p style="font-weight:bold;">Enter the description:</p>
        <input type="text" name="desc" placeholder="Enter the Anime Description"><br>
        <p style="font-weight:bold;">Total number of episodes:</p>
        <input type="text" name="seasons" placeholder="Enter the no.of episodes"><br>
        <p style="font-weight:bold;">Insert an image</p>
        <input type="file" name="img"><br>
        <button type="submit"style="position:absolute;top:120%;left:10%;background:blue;color:white">ADD DATA</button>
    </form>
</div>
{% endblock %}

anime/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    ANIME-PLAY
  </a>
     <a class="btn btn-primary" href="{% url 'animeapp:add_anime' %}">ADD Anime</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

anime/templates/delete.html
<form method="post">
  {% csrf_token %}
  Do you want to Delete This Anime?
  <button type="submit">YES</button>
</form>

anime/templates/detail.html
{% extends 'base.html' %}

{% block body %}<br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{anime.img.url}}" width="510px" height="300px">
        </div>
        <div class="col-md-6">
            <h4>{{anime.name}}</h4>
            <h5>{{anime.desc}}</h5>
            <h6>{{anime.seasons}}</h6>
            <a class="btn btn-warning" href="{% url 'animeapp:update' anime.id %}">EDIT</a>
            <a class="btn btn-danger" href="{% url 'animeapp:delete' anime.id %}">DELETE</a>
        </div>
    </div>
</div>
{% endblock %}

anime/templates/edit.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">UPDATE</button>
</form>

anime/templates/index.html
{% extends 'base.html' %}

{% block body %}<br>
<div class="container">
    <div class="row">
        {% for i in anime_list %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{{i.img.url}}" class="card-img-top" alt="" height="180px">
                  <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'animeapp:detail' i.id %}" class="btn btn-primary">Get Anime</a>
                  </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>



{% endblock %}